name: yolov10
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.3.0=py3.9_cpu_0
  - pip
  - pip:
      - aiofiles==23.2.1
      - altair==5.4.1
      - anyio==4.6.2.post1
      - fastapi==0.115.3
      - gradio==4.31.5
      - huggingface-hub==0.23.2
      - numpy==1.26.4
      - pandas==2.2.3
      - pydantic==2.9.2
      - requests==2.32.3
      - torch==2.3.0+cu121
      - torchaudio==2.3.0+cu121
      - torchvision==0.18.0+cu121
      - ultralytics==8.1.34
      - uvicorn==0.32.0
